### ISSUE TITLE
Doesn't work on Win10 - Load up a procmon csv export, and displays a empty selection box with 'apply'

### ISSUE THREAD

**Issue by rmusser01** [forensicxlab/VISION-ProcMon#1]
See title.

Clicking apply does not do anything.
Selecting the drop-down box shows no entries.

**Comment by forensicxlab** [comment]
Hello,
Thank you for reporting the issue. 
Please send the following information via email in order for me to investigate the issue: 
- The CSV you used. 
- Screenshots of the issue.

Kind regards.

**Comment by forensicxlab** [comment]
Hello rmusser01,
Thank you for providing the required information.

After investigating the issue you are facing here are my explanations :

- The CSV you exported is filtered. However, VISION-ProcMon require a fully exported capture to work (not filtered on a specific process).
- The "CreateFile" operation is not yet supported because it is creating to many nodes. I am working on a solution to maybe implement it.
- VISION-ProcMon is looking for the "Create Process" operation in order for the process to be visible (the why bellow).

As a reminder, this tool is meant be used to perform malware analysis "from scratch" which means taking a Procmon capture before starting the malware, run the malware, stop the capture, and finally make a full export (not filtered) CSV.

Hope I've helped.

Best Regards.
